name: proyecto_recetas
description: Aplicación móvil de recetas con IA

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.10.5+9
  path_provider: ^2.1.1
  http: ^1.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.1.0
  appwrite: ^11.0.0
  fl_chart: ^0.66.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true